<img src="https://dsiag.ch/images/dsi_rgb.png" alt="dsi logo" width="100" style="position: absolute; right: 0px;"/>

# Wöchentliche Todesfälle, 2010-2024

https://opendata.swiss/de/dataset/wochentliche-todesfalle-2010-20241

In [12]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

plt.rcParams["figure.figsize"] = (20, 10) 

url='https://dam-api.bfs.admin.ch/hub/api/dam/assets/31786122/master'

df = pd.read_csv(url, sep=';', encoding='ISO 8859-1', nrows=1042)
df['endend'] = pd.to_datetime(df.endend, dayfirst=True)
df

,Jahr,Woche,endend,Alter,AnzTF_HR,Erwartung,untGrenze,obeGrenze,Diff
0,2010,1,2010-01-10,0-64,193,195,159,231,.
1,2010,2,2010-01-17,0-64,198,195,159,231,.
2,2010,3,2010-01-24,0-64,191,194,158,230,.
3,2010,4,2010-01-31,0-64,207,194,158,229,.
4,2010,5,2010-02-07,0-64,175,193,157,229,.
...,...,...,...,...,...,...,...,...,...
1037,2014,48,2014-11-30,65+,1125,1123,1037,1209,.
1038,2014,49,2014-12-07,65+,1100,1140,1053,1227,.
1039,2014,50,2014-12-14,65+,1080,1149,1062,1237,.
1040,2014,51,2014-12-21,65+,1160,1158,1071,1246,.
1041,2014,52,2014-12-28,65+,1155,1167,1079,1255,.